### ISSUE TITLE
3440x1440 doesn't cover up the whole screen

### ISSUE THREAD

**Issue by sakifx9** [gennariarmando/tekken7-screen-patch#1]
there are some slight black bars on 3440x1440 but 2560x1080 covers up the whole screen

**Comment by gennariarmando** [comment]
That's weird, please try setting up the resolution first then close and relaunch the game.
If possible attach a screenshot, if it's still an issue i will look at it.

**Comment by sakifx9** [comment]
![image](https://user-images.githubusercontent.com/16516667/127742380-1a9cf358-0e39-4a17-ac6e-b7f6072a4448.png)
Skinny black bars on the side on 3440x1440

**Comment by gennariarmando** [comment]
[T7ScreenPatch.zip](https://github.com/gennariarmando/tekken7-screen-patch/files/6911495/T7ScreenPatch.zip)
Please try this and see if is fixed.

**Comment by sakifx9** [comment]
> [T7ScreenPatch.zip](https://github.com/gennariarmando/tekken7-screen-patch/files/6911495/T7ScreenPatch.zip)
> Please try this and see if is fixed.

![image](https://user-images.githubusercontent.com/16516667/127760054-20de48d1-c6ea-489f-9712-7382e820aad5.png)
Thanks, that has fixed the problem.
