### ISSUE TITLE
Camera distance difference

### ISSUE THREAD

**Issue by kelo221** [gennariarmando/tekken7-screen-patch#3]
Would it be possible to keep the same distance to the characters as with 16:9 monitors? As in the only fill in the black parts and keep the camera the same.
![aspect](https://user-images.githubusercontent.com/61495413/128782921-bca83c2d-d989-48f3-ae4f-e13afc99fbd4.gif)

**Comment by gennariarmando** [comment]
Yes, but you have to manually edit the field of view to achieve this.

https://github.com/gennariarmando/tekken7-screen-patch/blob/c2e9a75aece9456ee98bff961f08ffba1b2978b2/source/dllmain.cpp#L2

The link above shows which line you need to change, set it to 70 or higher.

**Comment by kelo221** [comment]
I set the FOV to 73 seems to be as good as it can get. Increasing it too much, to 90 for instance, causes the characters start too far from the camera. Must be coded to keep characters inside the camera.
73 FOV:
![aspect](https://user-images.githubusercontent.com/61495413/128950271-02da0863-7a1d-4650-bebb-ee0d33af904a.gif)
Here are the files if someone else wants them.
[Win64.zip](https://github.com/gennariarmando/tekken7-screen-patch/files/6965049/Win64.zip)
